lovelace:
  mode: yaml
  resources:
    - url: /local/logo.png
      type: image

input_boolean:
  demo_light:
    name: Demo Light
    initial: off
  demo_ac:
    name: Demo AC
    initial: off

automation: !include automations.yaml