- id: '1678886400000'
  alias: 'Reset Demo Booleans'
  description: 'Resets demo_light and demo_ac every 60 seconds'
  trigger:
    - platform: time_pattern
      seconds: '/60'
  action:
    - service: input_boolean.turn_off
      target:
        entity_id:
          - input_boolean.demo_light
          - input_boolean.demo_ac
  mode: single
