title: ORCA Display
views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: picture-entity
            image: /local/logo.png
            entity: input_boolean.orca_demo_ui_light
            show_name: false
            show_state: false
          - type: button
            tap_action:
              action: toggle
            entity: input_boolean.orca_demo_ui_light
            name: Light
          - type: button
            tap_action:
              action: toggle
            entity: input_boolean.orca_demo_ui_ac
            name: AC